name: BSE

run-name: Test Workflow

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:

    
jobs:
  myjob1:
    if: (github.event_name == 'push' || github.event_name == 'pull_request')
    strategy:
      fail-fast: false
      matrix:
        basis: [ sto-3g, 6-31++g ]
        format: [ json, nwchem ]
        elements: [ 8,p-17 ]
        
    runs-on: ubuntu-latest

    steps:
      - name: Pull docker image
        run: docker pull dulcetorres/bse

      - name: Run image
        run: docker run --rm -v $(pwd):data dulcetorres/bse ${{ matrix.basis }} ${{ matrix.format }} ${{ matrix.elements }}

      - name: Print results
        run: cat basis_set.${{ matrix.format }}
        
  myjob2:
    if: (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    
    steps:
      - name: Run image
        run: docker run --rm -v $(pwd):data dulcetorres/bse sto-3g json "1,2,10"

      - name: Print info
        run: cat basis_set.json
    

        
 

    
  
    
