name: BSE

run-name: Test Workflow

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

    
jobs:
  myjob:

    strategy:
      matrix:
        basis: [ sto-3g, 6-31++g ]
        format: [ json, nwchem ]
        elements: [ 1,6-8, C,8,p-17 ]

    runs-on: ubuntu-latest

    steps:
      - name: Pull docker image
        run: docker pull dulcetorres/bse

      - name: Run image
        run: docker run --rm -v $(pwd):data dulcetorres/bse ${{ matrix.basis }} ${{ matrix.format }} ${{ matrix.elements }}

      - name: Print results
        run: cat basis_set.${{ matrix.format }}
        
 

    
  
    
